// Code generated by mockery v1.1.2. DO NOT EDIT.

package repo

import mock "github.com/stretchr/testify/mock"

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

// GetLastNotifiedMessage provides a mock function with given fields:
func (_m *MockRepo) GetLastNotifiedMessage() (uint64, error) {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserData provides a mock function with given fields:
func (_m *MockRepo) GetUserData() (UserData, error) {
	ret := _m.Called()

	var r0 UserData
	if rf, ok := ret.Get(0).(func() UserData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(UserData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLastNotifiedMessage provides a mock function with given fields: _a0
func (_m *MockRepo) SetLastNotifiedMessage(_a0 uint64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
